[project]
name = "graspp-2025-spring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "folium>=0.19.5",
    "gradio>=5.29.0",
    "jupyter>=1.1.1",
    "lxml>=5.3.1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "selenium>=4.33.0",
    "statsmodels>=0.14.4",
    "streamlit>=1.45.0",
    "torch>=2.7.0",
    "wordcloud>=1.9.4",
]
